rightech:
  api-url: https://api.rightech.io
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2ODIzOGIwZTIwYjQ2ZGJiNmMxZjZiMmUiLCJzdWIiOiI2ODIzODdjYTIwYjQ2ZGJiNmMxZjZiMjkiLCJncnAiOiI2ODIyZmU5NTIwYjQ2ZGJiNmMxZjZhZjAiLCJvcmciOiI2ODIyZmU5NTIwYjQ2ZGJiNmMxZjZhZjAiLCJsaWMiOiI1ZDNiNWZmMDBhMGE3ZjMwYjY5NWFmZTMiLCJ1c2ciOiJhcGkiLCJmdWxsIjpmYWxzZSwicmlnaHRzIjoxLjUsImlhdCI6MTc0NzE1OTgyMiwiZXhwIjoxNzQ5NjY4NDAwfQ.fKkcL1-BFMQITfCxXnPJjupsLumVjxrkdE-KcU_YaZ0
  project-id: 682304b520b46dbb6c1f6af6

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:rightechProject_bot}
    token: ${TELEGRAM_BOT_TOKEN:7432499710:AAGBV6llMQWi18WN8bWY2f7i84US2L1Mx7U}

logging:
  level:
    root: INFO
    tgbot.rightech_bot: DEBUG
    org.springframework.web: DEBUG
    org.telegram.telegrambots: DEBUG 